---
- name: registers secrets through s3
  s3:
    bucket: "{{ item.value.bucket }}"
    object: "{{ item.value.object }}"
    mode: 'getstr'
    region: "{{ aws.region }}"
  register: secret
  with_dict: "{{ (secret|default({})).s3|default({}) }}"
  changed_when: false

- set_fact:
    secret: "{{ secret|default({}) | combine({ item.item.key: item.contents|from_json }) }}"
  with_items: "{{ (secret|default({})).results }}"
