---
- name: converts service files to a form that ansible can iterate over
  shell: |
      ruby -e "
        require 'json'
        packages = ARGV.first
        JSON.parse(packages).each do | type, targets |
          targets.each do | package, attributes |
            unless attributes.is_a? Hash
              packages[type][package]["version"] = attributes
            end
          end
        end

        puts packages.to_json
      " '{{ package|default({})|to_json }}'
  register: outs
- debug:
    msg: "{{ outs.stdout }}"
