---
- name: adds watch to log
  shell: |
      echo "
        /opt/loggly/configure-file-monitoring.sh \
          -a {{ service.loggly.user }} \
          -t {{ service.loggly.token }} \
          -u {{ service.loggly.user }} \
          -p {{ service.loggly.password }} \
          -f {{ item.key }}
      " > /tmp/test
  with_dict: "{{ log }}"
