---
- name: adds watch to log
  shell: |
      curl https://www.loggly.com/install/configure-file-monitoring.sh \
        > /tmp/configure-file-monitoring
      bash -c "
        configure-file-monitoring.sh \
          -a {{ service.loggly.user }} \
          -t {{ lookup('env', 'LOGGLY_TOKEN')}} -u callowaylc -f FILENAME -l ALIAS