---
- name: A changement management playbook for docker swarm services
  hosts: "{{ __target__ | default('all') }}"
  become: yes
  become_user: root
  become_method: sudo

  roles:
    #- packages
    #- secrets
    #- files
    - docker
