---
- name: A generic playbook for ingesting logs
  hosts: "{{ __target__ | default('all') }}"
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - packages
    - files
    - loggly
